version: '3.4'

networks:
  dev:
    driver: bridge
services:
  erflix.api:
    image: ${DOCKER_REGISTRY-}erflixapi
    depends_on:
     - "erflix.database"
    build:
      context: .
      dockerfile: erflix.API/Dockerfile
    ports:
      - "7261:443"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=5001
      - ASPNETCORE_HTTPS_PORTS=7261
      - ASPNETCORE_URLS=https://+:443
    volumes:
      - D:\erflix:/app/Files:rw
    networks:
      - dev
  erflix.database:
    image: postgres:latest
    container_name: erflix.database
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=erflixContext
    ports:
      - "5433:5432"
    volumes:
      - ./.containers/erflix_db:/var/lib/postgresql/data
    networks:
      - dev